### ISSUE TITLE
Release 1.0.3 is not available on Maven Central

### ISSUE THREAD

**Issue by quittle** [utluiz/jericho-selector#1]
Only 1.0 and 1.0.1 are available: http://repo1.maven.org/maven2/br/com/starcode/jerichoselector/jericho-selector/

**Comment by utluiz** [comment]
Oh, that was a mistake. The latest version is indeed 1.0.1. 

Mind this is not have yet all selectors and jQuery extensions implemented. However, if you do find bugs or some feature missing, please let me know.
